const testObj = {
  ccm_invoice_no: "test2",
  record_date: "2030-12-12",
  ccm_invoice_date: "2020-01-03",
  remark: null,
  is_complete: 1,
  cash_received_date: "2020-01-03",
  cash_paid_date: "2020-01-06",
  delivered_date: null,
  staff_id: 2,
  case_id: "test2",
  supplier_invoice_ref_no: null,
  supplier_purchase_order_ref_no: null,
  supplier_id: null,
  customer_id: 17,
  one_off_marketing_coupon_amount: 0,
  one_off_delivery_charge: 0,
  one_off_delivery_cost: 0,
  one_off_custom_discount: null,
};
